USE master;
GO
IF DB_ID (N'LLM_DB10') IS NOT NULL
ALTER DATABASE LLM_DB10 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE LLM_DB10;
GO

CREATE DATABASE LLM_DB10
ON PRIMARY
(
  NAME = lab10dat,
  FILENAME = '/var/opt/mssql/data/lab10.mdf',
  SIZE = 10,
  MAXSIZE = UNLIMITED,
  FILEGROWTH = 5%
)
LOG ON
(
  NAME = lab10log,
  FILENAME = '/var/opt/mssql/data/lab10log.ldf',
  SIZE = 5MB,
  MAXSIZE = 25MB,
  FILEGROWTH = 5MB
)
GO

---

USE LLM_DB10;
GO

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
  id int IDENTITY(1,1) PRIMARY KEY,
  email nvarchar(100) UNIQUE NOT NULL
        CHECK(LEN(email) > 6 AND email LIKE '%_@__%.__%'),
  phone_number char(11) NOT NULL CHECK(LEN(phone_number) = 11),
  registration_date date NOT NULL DEFAULT(GETDATE())
);
GO

INSERT INTO USERS(email, phone_number) VALUES
('email@mail.ru', '88005553535'),
('email@gmail.com', '79003241234'),
('user@yandex.ru', '74112341422'),
('user2@zmail.su', '73241234123');

GO

/*SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
	WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
	WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
COMMIT TRANSACTION;
GO*/

/*SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
	-- WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
	WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
COMMIT TRANSACTION;
GO*/

/*SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
	-- WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
	WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
COMMIT TRANSACTION;
GO*/

/*SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
	-- WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
	WAITFOR DELAY '00:00:06';
	SELECT * FROM USERS;
COMMIT TRANSACTION;
GO*/
