(define (ref array index . value)
  (define (f list index)
    (and (not (null? list))
        (if (= index 0)
            (car list)
            (f (cdr list) (- index 1)))))
  (define (g-rec list index value)
    (if (= index 0)
        (cons value list)
        (cons (car list) (g-rec (cdr list) (- index 1) value))))
  (define (g list index value . type)
    (and (not (> index (length list)))
        (if (null? type)
            (g-rec list index value)
            ((car type) (g-rec list index value)))))
  (if (null? value)
      (cond
        ((list? array) (f array index))
        ((vector? array) (f (vector->list array) index))
        ((string? array) (f (string->list array) index))
        (else #f))
      (cond
        ((list? array) (g array index (car value)))
        ((vector? array) (g (vector->list array) index (car value) list->vector))
        ((string? array) (and (char? (car value)) (g (string->list array) index (car value) list->string)))
        (else #f))))
